name: Workflow
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name $GITHUB_ACTOR
          git pull
          npm ci
          npm start
          git checkout gh-pages
          # git checkout -b gh-pages
          # git rm -rf .
          # git checkout master -- .gitignore
          mkdir -p questions
          mv docs questions
          git add . 
          git commit -m "auto update"
          git push origin gh-pages
