name: Workflow
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name $GITHUB_ACTOR
          git pull
          npm ci
          npm start
          git checkout -b gh-pages
          npm run push-gh-pages
